### ISSUE TITLE
Client failure may cause ds21 hang in server

### ISSUE THREAD

**Issue by jjhursey** [openpmix/openpmix#1233]
Thank you for taking the time to submit an issue!

### What version of the PMIx Reference Library are you using? (e.g., v1.0, v2.1, git master @ hash, etc.)

v3.1.2

### Please describe the system on which you are running

* Operating system/version: RHEL 7.5
* Computer hardware: ppc64le
* Network type: Infiniband, TCP
* Resource Manager: JSM

-----------------------------

## Details of the problem

We were running a scenario where we launched MPI processes then killed them quickly, often during `MPI_Init`. Occasionally we would see the PMIx server hang in the `ds21` code with the following stack:
```#0  0x00002000004a2c94 in __lll_lock_wait () from /lib64/libpthread.so.0
#1  0x000020000049b6dc in pthread_mutex_lock () from /lib64/libpthread.so.0
#2  0x0000200001143184 in pmix_ds21_lock_wr_get () from /path/to/pmix_install/lib/pmix/mca_gds_ds21.so
#3  0x000020000110ea34 in pmix_common_dstor_register_job_info () from /path/to/pmix_install/lib/libmca_common_dstore.so.1
#4  0x00002000011422fc in ds21_register_job_info () from /path/to/pmix_install/lib/pmix/mca_gds_ds21.so
#5  0x00002000002088d4 in server_switchyard () from /path/to/pmix_install/lib/libpmix.so.2
#6  0x000020000020a058 in pmix_server_message_handler () from /path/to/pmix_install/lib/libpmix.so.2
#7  0x000020000028c2f8 in pmix_ptl_base_process_msg () from /path/to/pmix_install/lib/libpmix.so.2
#8  0x000020000039d298 in event_process_active_single_queue (base=0x1023f140, activeq=0x1023f610, max_to_process=2147483647, endtime=0x0) at event.c:1646
#9  0x000020000039dd84 in event_process_active (base=0x1023f140) at event.c:1738```

The remaining clients on that host were still inside MPI_Init. One was waiting in `PMIx_Commit` and the other was in `PMIx_Init`.

I'm assuming that one of the clients was killed/died while still holding a ds21 lock. The server side of the ds21 may be trying to acquire that lock to write the job level data.

This should be able to be reproduced with `mpirun`/`prun`.

**Comment by rhc54** [comment]
No longer relevant
