### ISSUE TITLE
Testsuite crashes due to unaligned access on sparc64

### ISSUE THREAD

**Issue by glaubitz** [openpmix/openpmix#1596]
The testsuite crashes on sparc64 due to unaligned access:

```
make  check-TESTS
make[4]: Entering directory '/<<PKGBUILDDIR>>/test'
make[5]: Entering directory '/<<PKGBUILDDIR>>/test'
FAIL: run_tests03.pl
PASS: run_tests06.pl
FAIL: run_tests00.pl
FAIL: run_tests02.pl
FAIL: run_tests05.pl
FAIL: run_tests01.pl
FAIL: run_tests04.pl
PASS: run_tests09.pl
PASS: run_tests08.pl
PASS: run_tests12.pl
PASS: run_tests07.pl
PASS: run_tests10.pl
FAIL: run_tests11.pl
PASS: run_tests13.pl
PASS: run_tests15.pl
PASS: run_tests14.pl
========================================
   pmix 3.1.4rc2: test/test-suite.log
========================================

# TOTAL: 16
# PASS:  9
# SKIP:  0
# XFAIL: 0
# FAIL:  7
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: run_tests00.pl
====================

./pmix_test -n 4 --ns-dist 3:1 --fence "[db | 0:0-2;1:0]" 2>&1
Bus error

CODE 35328
FAIL run_tests00.pl (exit status: 138)

FAIL: run_tests01.pl
====================

./pmix_test -n 4 --ns-dist 3:1 --fence "[db | 0:;1:0]" 2>&1
Bus error

CODE 35328
FAIL run_tests01.pl (exit status: 138)

FAIL: run_tests02.pl
====================

./pmix_test -n 4 --ns-dist 3:1 --fence "[db | 0:;1:]" 2>&1
Bus error

CODE 35328
FAIL run_tests02.pl (exit status: 138)

FAIL: run_tests03.pl
====================

./pmix_test -n 4 --ns-dist 3:1 --fence "[0:]" 2>&1
Bus error

CODE 35328
FAIL run_tests03.pl (exit status: 138)

FAIL: run_tests04.pl
====================

./pmix_test -n 4 --ns-dist 3:1 --fence "[b | 0:]" 2>&1
Bus error

CODE 35328
FAIL run_tests04.pl (exit status: 138)

FAIL: run_tests05.pl
====================

./pmix_test -n 4 --ns-dist 3:1 --fence "[d | 0:]" --noise "[0:0,1]" 2>&1
Bus error

CODE 35328
FAIL run_tests05.pl (exit status: 138)

FAIL: run_tests11.pl
====================

./pmix_test -n 5 --test-resolve-peers --ns-dist "1:2:2" 2>&1
Bus error

CODE 35328
FAIL run_tests11.pl (exit status: 138)

============================================================================
Testsuite summary for pmix 3.1.4rc2
============================================================================
# TOTAL: 16
# PASS:  9
# SKIP:  0
# XFAIL: 0
# FAIL:  7
# XPASS: 0
# ERROR: 0
============================================================================
See test/test-suite.log
Please report to http://pmix.github.io/master
============================================================================
```

Full build log available at: https://buildd.debian.org/status/fetch.php?pkg=pmix&arch=sparc64&ver=3.1.4-1&stamp=1577756718&raw=0

**Comment by rhc54** [comment]
Is there any way you can obtain a backtrace from one or more of these segfaults so we can see where the unaligned memory access exists? Otherwise, this is going to be nearly impossible to track down as none of our developers have access to sparc64 machines.

**Comment by glaubitz** [comment]
Working on it. FWIW, access to a sparc64 machine can be obtained through the GCC compile farm, see: https://gcc.gnu.org/wiki/CompileFarm

**Comment by glaubitz** [comment]
Bisecting the issue just lead to the commit were the tests were separated from each other.

And running one of the failing scripts individually yields:

```
glaubitz@gcc202:~/openpmix/test$ ./run_tests11.pl
/usr/bin/timeout --preserve-status -k 35 30  ./pmix_test -n 5 --test-resolve-peers --ns-dist "1:2:2" 2>&1
Bus error

CODE 35328
glaubitz@gcc202:~/openpmix/test$
```

Running the ```pmix_test``` binary individually doesn't seem straight-forward:

```
glaubitz@gcc202:~/openpmix/test$ ./pmix_test -n 5 --test-resolve-peers --ns-dist "1:2:2"
--------------------------------------------------------------------------
Sorry!  You were supposed to get help about:
    pmix_init:startup:internal-failure
But I couldn't open the help file:
    /usr/local/share/pmix/help-pmix-runtime.txt: No such file or directory.  Sorry!
--------------------------------------------------------------------------
[gcc202:110517] PMIX ERROR: NOT-FOUND in file server/pmix_server.c at line 245
==110517== [1579619413.130392] ERROR [test_server.c:917:server_init]: Init failed with error -46
glaubitz@gcc202:~/openpmix/test$
```

**Comment by jjhursey** [comment]
It was mentioned that the root cause for this issue might be the same as Issue #1605 which now has a fix noted [here](https://github.com/openpmix/openpmix/issues/1605#issuecomment-582914796). Can you give the v3.1 branch a try to see if it resolves the issue?

**Comment by glaubitz** [comment]
Both the master and the v3.1 branch still crash due to unaligned access:

```
FAIL: run_tests00.pl
FAIL: run_tests01.pl
FAIL: run_tests02.pl
FAIL: run_tests03.pl
FAIL: run_tests04.pl
FAIL: run_tests05.pl
PASS: run_tests06.pl
PASS: run_tests07.pl
PASS: run_tests08.pl
PASS: run_tests09.pl
PASS: run_tests10.pl
FAIL: run_tests11.pl
PASS: run_tests12.pl
PASS: run_tests13.pl
PASS: run_tests14.pl
PASS: run_tests15.pl
============================================================================
Testsuite summary for pmix 3.1.5rc1
============================================================================
# TOTAL: 16
# PASS:  9
# SKIP:  0
# XFAIL: 0
# FAIL:  7
# XPASS: 0
# ERROR: 0
============================================================================
See test/test-suite.log
Please report to http://pmix.github.io/master
============================================================================
make[4]: *** [Makefile:1237: test-suite.log] Error 1
make[4]: Leaving directory '/home/glaubitz/openpmix/test'
make[3]: *** [Makefile:1345: check-TESTS] Error 2
make[3]: Leaving directory '/home/glaubitz/openpmix/test'
make[2]: *** [Makefile:1549: check-am] Error 2
make[2]: Leaving directory '/home/glaubitz/openpmix/test'
make[1]: *** [Makefile:1129: check-recursive] Error 1
make[1]: Leaving directory '/home/glaubitz/openpmix/test'
make: *** [Makefile:745: check-recursive] Error 1
glaubitz@gcc202:~/openpmix$ ./test/run_tests00.pl
/usr/bin/timeout --preserve-status -k 35 30  ./pmix_test -n 4 --ns-dist 3:1 --fence "[db | 0:0-2;1:0]" 2>&1
Bus error

CODE 35328
glaubitz@gcc202:~/openpmix$
```

Can you tell me how to run the ```pmix_test``` binary in GDB, so I can figure out where the unaligned access happens? Most likely it's just a matter of invalid pointer casting, i.e. something like explained here: https://wiki.sei.cmu.edu/confluence/display/c/EXP36-C.+Do+not+cast+pointers+into+more+strictly+aligned+pointer+types

**Comment by glaubitz** [comment]
Okay, I just used a coredump now which worked:

```
Core was generated by `/home/glaubitz/openpmix/test/.libs/pmix_test -n 4 --ns-dist 3:1 --fence [db | 0'.
Program terminated with signal SIGUSR1, User defined signal 1.
#0  0x00000100000108c0 in server_unpack_procs (buf=0xfff80001040137a0 "", size=296) at test_server.c:265
265                 ntasks = *(size_t *)ptr;
[Current thread is 1 (Thread 0xfff8000102c5f900 (LWP 220952))]
(gdb) bt
#0  0x00000100000108c0 in server_unpack_procs (buf=0xfff80001040137a0 "", size=296) at test_server.c:265
#1  0x0000010000011858 in _send_procs_cb (status=0, data=0xfff80001040137a0 "", ndata=296, cbdata=0x1000011d9e0, relfn=0x10000011d54 <_libpmix_cb>, 
    relcbd=0xfff80001040137a0) at test_server.c:461
#2  0x0000010000012800 in server_read_cb (fd=3, event=2, arg=0x1000011d9e0) at test_server.c:624
#3  0xfff80001006f4c84 in ?? () from /usr/lib/sparc64-linux-gnu/libevent-2.1.so.7
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```

The problem is the following code in ```server_unpack_procs```:

```
            server_id = *(int *)ptr;
            ptr += sizeof(int);

            nspace = ptr;
            ptr += PMIX_MAX_NSLEN+1;

            ntasks = *(size_t *)ptr;
            ptr += sizeof(size_t);

            ltasks = *(size_t *)ptr;
            ptr += sizeof(size_t);
```

**Comment by glaubitz** [comment]
This fixes the problem for me, I'll open a PR:

```
diff --git a/test/test_server.c b/test/test_server.c
index 50c154b8..24ac8c5b 100644
--- a/test/test_server.c
+++ b/test/test_server.c
@@ -248,7 +248,7 @@ static void server_unpack_procs(char *buf, size_t size)
     char *nspace;
 
     while ((size_t)(ptr - buf) < size) {
-        ns_count = *(size_t *)ptr;
+       memcpy (&ns_count, ptr, sizeof(size_t));
         ptr += sizeof(size_t);
 
         for (i = 0; i < ns_count; i++) {
@@ -256,16 +256,16 @@ static void server_unpack_procs(char *buf, size_t size)
             size_t ltasks, ntasks;
             int server_id;
 
-            server_id = *(int *)ptr;
+           memcpy (&server_id, ptr, sizeof(int));
             ptr += sizeof(int);
 
             nspace = ptr;
             ptr += PMIX_MAX_NSLEN+1;
 
-            ntasks = *(size_t *)ptr;
+           memcpy (&ntasks, ptr, sizeof(size_t));
             ptr += sizeof(size_t);
 
-            ltasks = *(size_t *)ptr;
+           memcpy (&ltasks, ptr, sizeof(size_t));
             ptr += sizeof(size_t);
 
             PMIX_LIST_FOREACH(tmp, server_nspace, server_nspace_t) {
@@ -287,7 +287,8 @@ static void server_unpack_procs(char *buf, size_t size)
             }
             size_t i;
             for (i = 0; i < ltasks; i++) {
-                int rank = *(int *)ptr;
+               int rank;
+               memcpy (&rank, ptr, sizeof(int));
                 ptr += sizeof(int);
                 if (ns_item->task_map[rank] >= 0) {
                     continue;
```

FWIW, this does not cost any performance as ```memcpy``` is just replaced by direct access on platforms with less strict alignment requirements.

**Comment by artpol84** [comment]
Thanks!
Good catch

**Comment by rhc54** [comment]
> FWIW, this does not cost any performance as memcpy is just replaced by direct access on platforms with less strict alignment requirements.

FWIW: this is just the test program, so performance isn't an issue. We use the ```memcpy``` method throughout the actual code base precisely for alignment reasons.

Thanks for the patch!
