### ISSUE TITLE
python-bindings build error with master

### ISSUE THREAD

**Issue by naughtont3** [openpmix/openpmix#1782]
Python-binding error during `make install` with latest master of openpmix

### What version of the PMIx Reference Library are you using? (e.g., v1.0, v2.1, git master @ hash, etc.)

master at 31f8408

### Describe how PMIx was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

git clone

### Please describe the system on which you are running

* Operating system/version: Linux
* Computer hardware: x86-64
* Network type:

-----------------------------

## Details of the problem

Things configure and compile fine, but the `make install` that runs the cython has an error.

```shell

...<snip>...

make[3]: Entering directory `/home/3t4/projects/ompi-x/scratch/HEALTHY-ROOK/source/openpmix-git-br-master/bindings/python'
/usr/bin/python3 ../../bindings/python/construct.py --src="../../include"
/usr/bin/python3 ../../bindings/python/setup.py build_ext --include-dirs="../../include" --library-dirs="/home/3t4/projects/ompi-x/scratch/HEALTHY-ROOK/source/openpmix-git-br-master/_install/lib" --user
Compiling pmix.pyx because it changed.
[1/1] Cythonizing pmix.pyx
warning: pmix.pxi:875:12: Unreachable code

Error compiling Cython file:
------------------------------------------------------------
...
            j = 0
            while NULL != regattrs[n].description[j]:
                PyMem_Free(regattrs[n].description[j])
                j += 1
            PyMem_Free(regattrs[n].description)
        if regattrs[n].info != NULL:
                     ^
------------------------------------------------------------

pmix.pxi:1595:22: Object of type 'pmix_regattr_t' has no attribute 'info'

Error compiling Cython file:
------------------------------------------------------------
...
            j = 0
            while NULL != regattrs[n].description[j]:
                PyMem_Free(regattrs[n].description[j])
                j += 1
            PyMem_Free(regattrs[n].description)
        if regattrs[n].info != NULL:
                           ^
------------------------------------------------------------

pmix.pxi:1595:28: Invalid types for '!=' (Python object, void *)

Error compiling Cython file:
------------------------------------------------------------
...
            while NULL != regattrs[n].description[j]:
                PyMem_Free(regattrs[n].description[j])
                j += 1
            PyMem_Free(regattrs[n].description)
        if regattrs[n].info != NULL:
            pmix_free_info(regattrs[n].info, regattrs[n].ninfo)
                                     ^
------------------------------------------------------------

pmix.pxi:1596:38: Object of type 'pmix_regattr_t' has no attribute 'info'

Error compiling Cython file:
------------------------------------------------------------
...
            while NULL != regattrs[n].description[j]:
                PyMem_Free(regattrs[n].description[j])
                j += 1
            PyMem_Free(regattrs[n].description)
        if regattrs[n].info != NULL:
            pmix_free_info(regattrs[n].info, regattrs[n].ninfo)
                                                       ^
------------------------------------------------------------

pmix.pxi:1596:56: Object of type 'pmix_regattr_t' has no attribute 'ninfo'

Error compiling Cython file:
------------------------------------------------------------
...
            while NULL != regattrs[n].description[j]:
                PyMem_Free(regattrs[n].description[j])
                j += 1
            PyMem_Free(regattrs[n].description)
        if regattrs[n].info != NULL:
            pmix_free_info(regattrs[n].info, regattrs[n].ninfo)
                                     ^
------------------------------------------------------------

pmix.pxi:1596:38: Cannot convert Python object to 'pmix_info_t *'

Error compiling Cython file:
------------------------------------------------------------
...
                    pmix_copy_key(regattrs[n].string, attr['key'])
                    regattrs[n].type = attr['val_type']
                    nstrings         = len(attr['description'])

                    # allocate and load pmix info structs from python list of dictionaries
                    regattrs[n].ninfo = 0
                              ^
------------------------------------------------------------

pmix.pyx:1627:31: Object of type 'pmix_regattr_t' has no attribute 'ninfo'

Error compiling Cython file:
------------------------------------------------------------
...
                    regattrs[n].type = attr['val_type']
                    nstrings         = len(attr['description'])

                    # allocate and load pmix info structs from python list of dictionaries
                    regattrs[n].ninfo = 0
                    info_ptr          = &(regattrs[n].info)
                                                    ^
------------------------------------------------------------

pmix.pyx:1628:53: Object of type 'pmix_regattr_t' has no attribute 'info'

Error compiling Cython file:
------------------------------------------------------------
...
                    regattrs[n].type = attr['val_type']
                    nstrings         = len(attr['description'])

                    # allocate and load pmix info structs from python list of dictionaries
                    regattrs[n].ninfo = 0
                    info_ptr          = &(regattrs[n].info)
                                       ^
------------------------------------------------------------

pmix.pyx:1628:40: Cannot take address of Python object attribute 'info'

Error compiling Cython file:
------------------------------------------------------------
...
                    nstrings         = len(attr['description'])

                    # allocate and load pmix info structs from python list of dictionaries
                    regattrs[n].ninfo = 0
                    info_ptr          = &(regattrs[n].info)
                    rc                = pmix_alloc_info(info_ptr, &(regattrs[n].ninfo), attr['info'])
                                                                              ^
------------------------------------------------------------

pmix.pyx:1629:79: Object of type 'pmix_regattr_t' has no attribute 'ninfo'

Error compiling Cython file:
------------------------------------------------------------
...
                    nstrings         = len(attr['description'])

                    # allocate and load pmix info structs from python list of dictionaries
                    regattrs[n].ninfo = 0
                    info_ptr          = &(regattrs[n].info)
                    rc                = pmix_alloc_info(info_ptr, &(regattrs[n].ninfo), attr['info'])
                                                                 ^
------------------------------------------------------------

pmix.pyx:1629:66: Cannot take address of Python object attribute 'ninfo'

Error compiling Cython file:
------------------------------------------------------------
...
                nattrs = 0
        else:
            nattrs = 0

        # call Server API
        rc = PMIx_Register_attributes(func, regattrs, nattrs)
                                    ^
------------------------------------------------------------

pmix.pyx:1648:37: Call with wrong number of arguments (expected 2, got 3)
Traceback (most recent call last):
  File "../../bindings/python/setup.py", line 48, in <module>
    compiler_directives={'language_level': 3})
  File "/usr/lib64/python3.6/site-packages/Cython/Build/Dependencies.py", line 1026, in cythonize
    cythonize_one(*args)
  File "/usr/lib64/python3.6/site-packages/Cython/Build/Dependencies.py", line 1146, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: pmix.pyx
make[3]: *** [install-exec-local] Error 1
make[3]: Leaving directory `/home/3t4/projects/ompi-x/scratch/HEALTHY-ROOK/source/openpmix-git-br-master/bindings/python'
make[2]: *** [install-am] Error 2
make[2]: Leaving directory `/home/3t4/projects/ompi-x/scratch/HEALTHY-ROOK/source/openpmix-git-br-master/bindings/python'
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory `/home/3t4/projects/ompi-x/scratch/HEALTHY-ROOK/source/openpmix-git-br-master/bindings'
make: *** [install-recursive] Error 1
ERROR: OPENPMIX failed
[3t4@node0 HEALTHY-ROOK]$ 
```

**Comment by naughtont3** [comment]
OK, looks like `PMIx_Register_attributes()` has additional 3rd arg now `nattrs`.

**Comment by rhc54** [comment]
Ah - nuts. I'll fix it. Thanks!
