### ISSUE TITLE
Segfault in PMIx_tool_attach_to_server

### ISSUE THREAD

**Issue by dirk-schubert-arm** [openpmix/openpmix#1852]
### What version of the PMIx Reference Server / PMIx are you using?
Latest master.

### Please describe the system on which you are running

- Operating system/version: Ubuntu 18.04
- Computer hardware: x86-64

-----------------------------

## Details of the problem

The reproducer to demonstrate the PMIx_tool_attach_to_server segfault is done using the MPIR-shim as this was the easiest way, but it's not limited to it and can be reproduced independently.

Steps to reproduce:

```shell
# # symlink mpirun to prte - for example with:
$ (cd $(dirname $(which prte)) && ln -s prte mpirun)
$ ./src/mpir mpirun -n 1 ./hello
[e124324:22192] PMIX ERROR: UNPACK-FAILURE in file tool/pmix_tool.c at line 170
Segmentation fault (core dumped)
```

When run under GDB:

```
$ gdb --args ./src/mpir mpirun -n 1 ./hello
(gdb) run
Thread 1 "mpir" received signal SIGSEGV, Segmentation fault.
0x00000000004ac1eb in PMIx_tool_attach_to_server (myproc=0x8720c0 <myproc>, server=0x0, info=0x8ff2b0, ninfo=3) at tool/pmix_tool.c:1511
1511	        PMIX_LOAD_PROCID(&ps->server, peer->info->pname.nspace, peer->info->pname.rank);
(gdb) bt
#0  0x00000000004ac1eb in PMIx_tool_attach_to_server (myproc=0x8720c0 <myproc>, server=0x0, info=0x8ff2b0, ninfo=3) at tool/pmix_tool.c:1511
#1  0x00000000004abefe in PMIx_tool_connect_to_server (proc=0x8720c0 <myproc>, info=0x8ff2b0, ninfo=3) at tool/pmix_tool.c:1463
#2  0x00000000004084c2 in connect_to_server () at /opt/gcc/8.3.0/include/c++/8.3.0/bits/stl_iterator.h:783
#3  mpir(int, char**) () at mpir.cxx:1919
#4  0x00007ffff6883b97 in __libc_start_main (main=0x405d30 <main(int, char**)>, argc=5, argv=0x7fffffffa0c8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffa0b8) at ../csu/libc-start.c:310
#5  0x0000000000405eda in _start () at /opt/gcc/8.3.0/include/c++/8.3.0/bits/stl_tree.h:211
```

I am aware that PMIx_tool_connect_to_server is deprecated. Howerver, using PMIx_tool_attach_to_server with a non-NULL "server" passed in (not sure if that matters), caused the same segfault.

**Comment by dirk-schubert-arm** [comment]
@rhc54: Can you have a look? Thanks.

**Comment by rhc54** [comment]
This has been fixed in PMIx master
