### ISSUE TITLE
SEGV during PMIx_Finalize

### ISSUE THREAD

**Issue by alex--m** [openpmix/openpmix#1989]
It looks like the root cause is elsewhere (insufficient/incorrect cleanup in OMPI's ptl_tcp) - but this SEGV on cleanup probably shouldn't happen regardless. This crash is consistent with the new version, so it should be easy to reproduce - let me know if there's anything I can do to help.

## Background information

Build from latest (maybe a few days old) OMPI master:
````
$ ~/ompi/build/bin/ompi_info
                 Package: Open MPI amargolin@thunder00 Distribution
                Open MPI: 5.0.0a1
  Open MPI repo revision: v2.x-dev-8246-gc06dfc58f2
   Open MPI release date: Unreleased developer copy
                 MPI API: 3.1.0
            Ident string: 5.0.0a1
...

$ git submodule status
 2e3df8ee02bd21e20a3675f580eccc38cbe014a4 3rd-party/openpmix (v4.0.0rc1)
````

### Please describe the system on which you are running

* Operating system/version: CentOS 8.2, kernel 5.10
* Computer hardware: a single 2-socket Xeon server
* Network type: N/A (happens on a single host) 

-----------------------------

## Details of the problem

Command-line:
`~/ompi/build/bin/mpirun -n 4 -x DISPLAY xterm -e gdb ~/osu_coll/osu_allreduce`

Resulting crash (with some details):
````
Thread 1 "osu_allreduce" received signal SIGSEGV, Segmentation fault.
var_destructor (var=0x6c4350) at pmix_mca_base_var.c:1873
1873            NULL != var->mbv_storage->stringval) {
Missing separate debuginfos, use: yum debuginfo-install hwloc-libs-1.11.9-3.el8.x86_64 libibverbs-29.0-3.el8.x86_64 libnl3-3.5.0-1.el8.x86_64 librdmacm-29.0-3.el8.x86_64 libtool-ltdl-2.4.6-25.el8.x86_64 numactl-libs-2.0.12-11.el8.x86_64 zlib-1.2.11-16.el8_2.x86_64
(gdb) bt
#0  var_destructor (var=0x6c4350) at pmix_mca_base_var.c:1873
#1  0x00007ffff6190a80 in pmix_obj_run_destructors (object=0x6c4350) at /mnt/central/testing/src/ompi/3rd-party/openpmix/src/class/pmix_object.h:465
#2  0x00007ffff619303c in pmix_mca_base_var_finalize () at pmix_mca_base_var.c:1148
#3  0x00007ffff614f1f3 in pmix_rte_finalize () at runtime/pmix_finalize.c:105
#4  0x00007ffff60d12aa in PMIx_Finalize (info=0x0, ninfo=0) at client/pmix_client.c:1029
#5  0x00007ffff7b1ce3f in ompi_rte_finalize () at runtime/ompi_rte.c:903
#6  0x00007ffff7b11bb8 in ompi_mpi_finalize () at runtime/ompi_mpi_finalize.c:468
#7  0x00007ffff7b33d35 in PMPI_Finalize () at pfinalize.c:54
#8  0x0000000000401ab2 in main (argc=<optimized out>, argv=<optimized out>) at osu_allreduce.c:133
(gdb) p *var
$1 = {super = {obj_magic_id = 0, obj_class = 0x7ffff6457940 <pmix_mca_base_var_t_class>, obj_reference_count = 0, 
    cls_init_file_name = 0x7ffff6222dd1 "pmix_mca_base_var.c", cls_init_lineno = 1406}, mbv_index = 91, mbv_group_index = 30, mbv_info_lvl = PMIX_INFO_LVL_2, 
  mbv_type = PMIX_MCA_BASE_VAR_TYPE_STRING, mbv_variable_name = 0x6c44f0 "if_include", mbv_full_name = 0x6c4510 "ptl_tcp_if_include", 
  mbv_long_name = 0x6c4530 "pmix_ptl_tcp_if_include", mbv_synonyms = {super = {obj_magic_id = 16046253926196952813, 
      obj_class = 0x7ffff644e520 <pmix_value_array_t_class>, obj_reference_count = 1, cls_init_file_name = 0x7ffff6222dd1 "pmix_mca_base_var.c", 
      cls_init_lineno = 1860}, array_items = 0x6c4430 "", array_item_sizeof = 4, array_size = 0, array_alloc_size = 1}, 
  mbv_flags = (PMIX_MCA_BASE_VAR_FLAG_DEPRECATED | unknown: 196608), mbv_scope = PMIX_MCA_BASE_VAR_SCOPE_LOCAL, mbv_source = PMIX_MCA_BASE_VAR_SOURCE_DEFAULT, 
  mbv_synonym_for = 90, 
  mbv_description = 0x6c4450 "Comma-delimited list of devices and/or CIDR notation of TCP networks (e.g., \"eth0,192.168.0.0/16\").  Mutually exclusive with ptl_tcp_if_exclude.", mbv_source_file = 0x0, mbv_enumerator = 0x0, mbv_bind = 0, mbv_storage = 0x7ffff3d864d0, mbv_file_value = 0x0}
(gdb) l
1868    static void var_destructor(pmix_mca_base_var_t *var)
1869    {
1870        if ((PMIX_MCA_BASE_VAR_TYPE_STRING == var->mbv_type ||
1871                    PMIX_MCA_BASE_VAR_TYPE_VERSION_STRING == var->mbv_type) &&
1872            NULL != var->mbv_storage &&
1873            NULL != var->mbv_storage->stringval) {
1874            free (var->mbv_storage->stringval);
1875            var->mbv_storage->stringval = NULL;
1876        }
1877
(gdb) f 8
#8  0x0000000000401ab2 in main (argc=<optimized out>, argv=<optimized out>) at osu_allreduce.c:133
133         MPI_CHECK(MPI_Finalize());
(gdb) 

````

**Comment by rhc54** [comment]
Hmmm...well, first thing is that OMPI doesn't have a ptl/tcp component. The "ptl" framework is in PMIx (the Pmix Transport Layer). However, OMPI master is now using PMIx v4.0.0, which doesn't have a "tcp" component in it - we removed that component and refactored it. So if you are seeing a "ptl/tcp" component being loaded, then that means you have a stale installation.

You likely need to "rm -rf \<ompi-prefix\>" and re-install. Should fix the problem.

**Comment by alex--m** [comment]
@rhc54 right you are, thanks!
