### ISSUE TITLE
Python bindings fail on install

### ISSUE THREAD

**Issue by jjhursey** [openpmix/openpmix#2079]
I'm running with `master` and discovered the following build issue with the Python bindings.

```
./configure --prefix=/home/pmixer/tmp-build-CB5NR/install-pmix \
    --with-libevent=/home/pmixer/local/libevent --with-hwloc=/home/pmixer/local/hwloc \
    --enable-python-bindings
make -j 20
make -j 20 install
```

The `make install` will fail with this message:
```
make[2]: Entering directory `/home/pmixer/tmp-build-CB5NR/openpmix/bindings/python'
make[3]: Entering directory `/home/pmixer/tmp-build-CB5NR/openpmix/bindings/python'
/usr/bin/python3 ../../bindings/python/construct.py --src="../../include" --include-dir="../../include"
make[3]: Nothing to be done for `install-data-am'.
BAD DIMENSION 2
make[3]: *** [install-exec-local] Error 1
make[3]: Leaving directory `/home/pmixer/tmp-build-CB5NR/openpmix/bindings/python'
make[2]: *** [install-am] Error 2
make[2]: Leaving directory `/home/pmixer/tmp-build-CB5NR/openpmix/bindings/python'
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory `/home/pmixer/tmp-build-CB5NR/openpmix/bindings'
make: *** [install-recursive] Error 1
```

**Comment by rhc54** [comment]
I found it - noodling over the fix

**Comment by jjhursey** [comment]
Still failing
 * https://github.com/openpmix/openpmix/pull/2080#issuecomment-789133950

**Comment by jjhursey** [comment]
Some notes:
 * Building with `Cython: yes (0.19)` failed
 * Building with `Cython: yes (0.29.21)` passed for Ralph, but failed with `(0.29.22)` for me.

Failure is:
```
/usr/bin/python3 ../../bindings/python/construct.py --src="../../include" --include-dir="../../include"
make[3]: Nothing to be done for `install-data-am'.
Traceback (most recent call last):
  File "../../bindings/python/construct.py", line 530, in <module>
    main()
  File "../../bindings/python/construct.py", line 516, in main
    harvest_constants(options, "pmix.h", constants, definitions)
  File "../../bindings/python/construct.py", line 30, in harvest_constants
    lines = inputfile.readlines()
  File "/usr/lib64/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 217: ordinal not in range(128)
```
